// <auto-generated />
using System;
using Kitchen.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Kitchen.Infrastructure.Migrations
{
    [DbContext(typeof(KitchenDbContext))]
    [Migration("20250718165918_AdicionaColunaDisponibilidade")]
    partial class AdicionaColunaDisponibilidade
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.18")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Kitchen.Domain.Entities.PedidoEmPreparo", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("ClienteId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("FormaDeEntrega")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Justificativa")
                        .HasColumnType("text");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("Pedidos");
                });

            modelBuilder.Entity("Kitchen.Domain.Entities.PedidoEmPreparo", b =>
                {
                    b.OwnsMany("Kitchen.Domain.Entities.ItemPreparo", "Itens", b1 =>
                        {
                            b1.Property<Guid>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("uuid");

                            b1.Property<string>("NomeProduto")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("character varying(100)");

                            b1.Property<Guid>("PedidoId")
                                .HasColumnType("uuid");

                            b1.Property<Guid>("ProdutoId")
                                .HasColumnType("uuid");

                            b1.Property<int>("Quantidade")
                                .HasColumnType("integer");

                            b1.HasKey("Id");

                            b1.HasIndex("PedidoId");

                            b1.ToTable("ItemPreparo");

                            b1.WithOwner()
                                .HasForeignKey("PedidoId");
                        });

                    b.Navigation("Itens");
                });
#pragma warning restore 612, 618
        }
    }
}
